### PR TITLE
feat: Introduce Workspace Support for Multi-Tenant and Environment Separation

### PR DESCRIPTION
**Pull request by christianmat**
### Overview
This PR introduces the concept of **workspaces** in Trench, enabling the separation of data across different environments and tenants within a single Trench cluster. By incorporating workspaces, we can logically partition data, allowing for better multi-tenancy support and isolated environments, which is essential for organizations managing multiple projects or clients in a single analytics setup.

### Why did I build this?
Workspaces provide the following benefits:
- **Data Partitioning:** Each workspace represents a unique scope, making it easy to keep data separate for different clients, environments, or projects.
- **Environment Isolation:** By creating separate workspaces for staging, testing, and production environments, organizations can ensure that data flows only where intended, avoiding accidental cross-environment contamination.
- **Simplified Access Control:** Workspaces make it possible to manage API keys and permissions at a workspace level, allowing tighter control over who can access data within each workspace.
  
These additions empower users to safely consolidate data collection within a single Trench instance while maintaining clear boundaries between tenants and environments.

### Implementation details
- Created a `workspaces` and `api_keys` table to the main/default database
- Added logic to automatically bootstrap the default workspace.
- Added a new /workspaces endpoint for creating new workspaces.
- Added bootstrap logic that automatically creates a new database and kafka topic per workspace
- Added routing logic to the API Guards such that data is automatically routed to the right ClickHouse database and Kafka topic

### Backwards compatibility
- Fully backward compatible with existing Trench server versions
- API keys will automatically be bootstrapped from the .env file

### Testing Done
- **Unit Tests:** Added unit tests on critical code paths
- **Integration Tests:** Verified existing e2e tests passed
- **Manual Testing:** Performed manual tests on:
  - Creating new workspaces and verifying their isolation from other workspaces.
  - Generating and validating API keys unique to each workspace.
  - Running queries to ensure data retrieval is restricted to the specified workspace context.

These tests confirm that workspace support operates as intended and maintains data separation and integrity across various use cases.

### Reviews requested
We open this PR for anyone to review the code, comment on the implementation, and to give general feedback on this feature.

### CODE REVIEW

**Comment by esadek** [comment]
> Added a `workspace_id` column to the `events` table for associating each event with a specific workspace.

Will events from all workspaces be sent to the same `events` table in ClickHouse?
In the case of development, staging and production workspaces it would be nice to have separate schemas in ClickHouse. Otherwise all queries would need to filter on `workspace_id`.

**Comment by christianmat** [comment]
> > Added a `workspace_id` column to the `events` table for associating each event with a specific workspace.
> 
> Will events from all workspaces be sent to the same `events` table in ClickHouse? In the case of development, staging and production workspaces it would be nice to have separate schemas in ClickHouse. Otherwise all queries would need to filter on `workspace_id`.

@esadek correct -- we solve this in the `/queries` endpoint by appending all queries with the `workspace_id` ([source](https://github.com/FrigadeHQ/trench/pull/18/files#diff-678e9a6f4f82e4b6e7138a54eb89642af4441ff05cfc3a66d3e375595334d30a)) based on the current API key. May be a bit funky, but all my unit tests seem to pass. So to the end-user, the concept of workspaces is automatically abstracted away.

That being said, in the case where you want separate Trench instances without worrying about data from different workspaces getting intermingled, I recommend just spinning up separate Docker images per environment and just using the default workspace created in each one.

What do you think?

**Comment by esadek** [comment]
> @esadek correct -- we solve this in the `/queries` endpoint by appending all queries with the `workspace_id` ([source](https://github.com/FrigadeHQ/trench/pull/18/files#diff-678e9a6f4f82e4b6e7138a54eb89642af4441ff05cfc3a66d3e375595334d30a)) based on the current API key. May be a bit funky, but all my unit tests seem to pass. So to the end-user, the concept of workspaces is automatically abstracted away.
> 
> That being said, in the case where you want separate Trench instances without worrying about data from different workspaces getting intermingled, I recommend just spinning up separate Docker images per environment and just using the default workspace created in each one.
> 
> What do you think?

@christianmat I think it would be nice to support separate databases or schemas for each workspace, instead of needing a different Trench/ClickHouse instance for each environment to separate data. Development and staging should be very low volume compared to production so having completely separate Trench instances feels a bit excessive. I've seen a lot of companies separate dev, staging and prod data by database or schema in Snowflake, Redshift and BigQuery.

With data from all workspaces syncing to the same `events` table, anyone querying the data directly from ClickHouse would need to understand what `workspace_id` is, which `workspace_id` they need, and make sure they are filtering for the correct workspace in their queries. This is not a problem if you have a "production" database or schema.

**Comment by christianmat** [comment]
@esadek I see what you're saying. I don't like the idea of hardcoding specific environments as it's less flexible. But maybe a good solution would be to create a database for each workspace automatically. I am gonna do some research to see if this is feasible. That way we get the flexibility of having as many environments/workspaces as needed without introducing new concepts (e.g. having `workspace_id` in all queries). Does that make sense?

**Comment by christianmat** [comment]
@esadek I see what you're saying. I don't like the idea of hardcoding specific environments as it's less flexible. But maybe a good solution would be to create a database for each workspace automatically. I am gonna do some research to see if this is feasible. That way we get the flexibility of having as many environments/workspaces as needed without introducing new concepts (e.g. having workspace_id in all queries). Does that make sense?

**Comment by esadek** [comment]
@christianmat Yes, automatically creating a database for each workspace would be great.

**Comment by christianmat** [comment]
@esadek can I get your 👀 on this? It's now updated to automatically create a ClickHouse database and kafka topic per workspace.

**Comment by esadek** [comment]
@christianmat Is there documentation for the /workspace endpoint?

**Comment by christianmat** [comment]
> @christianmat Is there documentation for the /workspace endpoint?

@esadek Yes, I've added swagger spec for it. I will create an official documentation page once the feature has been battle tested a bit.

**Pull request merged**
